package com.codeit.mopl.event.entity;

public enum EventType {
  NOTIFICATION_CREATED,
  DIRECT_MESSAGE_CREATED,
  FOLLOWER_INCREASE,
  FOLLOWER_DECREASE,
  NOTIFICATION_CREATE,
  PLAY_LIST_CREATED,
  WATCH_SESSION_CREATED,
  MAIL_SEND
}
